"""iv_engine — Python bindings for the Rust numerical core.

All numerical work happens in Rust. Batch APIs in [`iv_engine.batch`] accept
NumPy arrays or pandas ``Series`` and run in parallel by default.
"""

from __future__ import annotations

from iv_engine._core import (
    IVError,
    __version__,
    black_intrinsic,
    black_price,
    black_price_total_vol,
    black_scholes_delta,
    black_scholes_forward,
    black_scholes_gamma,
    black_scholes_price,
    black_scholes_theta,
    black_scholes_vanna,
    black_scholes_vega,
    black_scholes_vomma,
    delta,
    gamma,
    implied_volatility,
    log_moneyness,
    norm_cdf,
    norm_cdf_c,
    norm_cdf_cs,
    norm_cdfs,
    norm_pdf,
    norm_pdfs,
    normalised_implied_volatilities,
    normalised_implied_volatility,
    theta,
    vanna,
    vega,
    vomma,
)
from iv_engine.batch import (
    black_prices,
    black_scholes_prices,
    deltas,
    gammas,
    implied_volatilities,
    vegas,
)

__all__ = [
    "IVError",
    "__version__",
    "black_intrinsic",
    "black_price",
    "black_price_total_vol",
    "black_prices",
    "black_scholes_delta",
    "black_scholes_forward",
    "black_scholes_gamma",
    "black_scholes_price",
    "black_scholes_prices",
    "black_scholes_theta",
    "black_scholes_vanna",
    "black_scholes_vega",
    "black_scholes_vomma",
    "delta",
    "deltas",
    "gamma",
    "gammas",
    "implied_volatilities",
    "implied_volatility",
    "log_moneyness",
    "norm_cdf",
    "norm_cdf_c",
    "norm_cdf_cs",
    "norm_cdfs",
    "norm_pdf",
    "norm_pdfs",
    "normalised_implied_volatilities",
    "normalised_implied_volatility",
    "theta",
    "vanna",
    "vega",
    "vegas",
    "vomma",
]
